version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    schedule:
      interval: "daily"
    assignees:
      - "Tamschi"
    reviewers:
      - "Tamschi"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Tamschi"
    reviewers:
      - "Tamschi"
