language: rust
rust:
  - 1.40.0
  - stable
  - beta
  - nightly
stages:
  - ensure format
  - deny warnings
  - test
script:
  - cargo +$TRAVIS_RUST_VERSION test
jobs:
  include:
    - stage: ensure format
      if: branch = develop
      script:
        - rustup toolchain install nightly --profile minimal --component rustfmt
        - cargo +nightly fmt -- --check
    - stage: deny warnings
      if: branch = develop
      script:
        - rustup toolchain install nightly --profile minimal --component clippy
        - RUSTFLAGS='-D warnings' cargo +nightly build --all-targets
  allow_failures:
    - rust: nightly
  fast_finish: true
# cache: cargo # Caching Cargo seems to build up cache size until Travis CI grinds to a halt.
