# See <https://handsonappsec.medium.com/automerge-github-dependabot-alerts-with-github-actions-7cd6f5763750>.
# Modified to only approve and let Dependabot do the merge if CI goes through.

name: 'Auto-Approve Dependabot'
on:
  pull_request:
jobs:
  approve-dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: auto-approve
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.AutoApproveDependabotToken}}
          script: |
            // See <https://octokit.github.io/rest.js/v18#pulls>,
            // <https://github.com/marketplace/actions/github-script#welcome-a-first-time-contributor>.
            const reviews = await github.pulls.listReviews({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
            });

            for (review of reviews.data) {
              console.log(`A review exists. Exiting.`)
              return;
            }

            await github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: '[Auto-Approve Dependabot]\n@dependabot merge',
            });
