# Largely inspired by https://github.com/dtolnay/syn/blob/master/.github/workflows/ci.yml under MIT OR Apache-2.0.
name: CI
on:
  pull_request:
  push:
  schedule: [cron: "0 8 * * 5"] # 8:00 on Fridays

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-01-07
        profile: minimal
    - run: cat CI.toml >> Cargo.toml
    # See <https://docs.platformio.org/en/latest/integration/ci/github-actions.html>.
    - uses: actions/setup-python@v2
    - run: python -m pip install --upgrade pip
    - run: pip install --upgrade platformio
    - run: pio run
