# See <https://handsonappsec.medium.com/automerge-github-dependabot-alerts-with-github-actions-7cd6f5763750>.
# Modified to only approve and let Dependabot do the merge if CI goes through.

name: 'Auto-Approve Dependabot'
on:
  pull_request:
jobs:
  approve-dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: auto-approve
        uses: actions/github-script@4.0.2
        with:
          script: |
            if ((await github.pulls.listReviews({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              per_page: 1,
            })).length > 0) {
              console.log("A review exists. Exiting.")
              return;
            }
            github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: '[Auto-Approve Dependabot]\n@dependabot merge',
            });
          github-token: ${{github.token}}
