# labels.json adapted from <https://raw.githubusercontent.com/seantrane/github-label-presets/master/labels.json>.
# See also <https://seantrane.com/posts/logical-colorful-github-labels-18230/>.

name: Update Labels
on:
  push:
    branches: [develop]

jobs:
  deny-warnings:
    name: Update Labels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm
    - run: npx github-label-sync
        --dry-run
        --access-token ${{ secrets.GITHUB_TOKEN }}
        --labels labels.json
        ${{ github.repository }}
