name: Zulip Automation

permissions: # None should be needed.

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  touch_zulip_stream:
    name: Touch Zulip Stream
    runs-on: ubuntu-latest
    steps:
      - run: 'curl -X POST https://iteration-square-automation.schichler.dev/.netlify/functions/touch_project_stream --data-raw ${{ github.repository }} --header "Authorization: ${{ secrets.GITHUB_TOKEN }}"'
